/* Placeholder for DoJa v48 Empty. build-doja.bat overwrites this file. */
#ifndef PSTROS_STANDALONE_GAME_H
#define PSTROS_STANDALONE_GAME_H
#define DOJA_PORT_BUILD_VERSION 48
#define DOJA_PORT_VERSION_TEXT "v48 Empty"
#define STANDALONE_APP_NAME "EMPTY"
#define STANDALONE_MAIN_CLASS "Main"
#define DOJA_APP_CLASS "Main"
#define DOJA_APP_PARAM "0"
#define DOJA_CANVAS_WIDTH 240
#define DOJA_CANVAS_HEIGHT 240
#define DOJA_LOGICAL_WIDTH 240
#define DOJA_LOGICAL_HEIGHT 240
#define DOJA_SCREEN_X 8
#define DOJA_SCREEN_Y -24
#define DOJA_HW_AFFINE_SCALE 0
#define DOJA_OUTPUT_X 0
#define DOJA_OUTPUT_Y 0
#define DOJA_OUTPUT_WIDTH 256
#define DOJA_OUTPUT_HEIGHT 192
#define DOJA_BG_PA 256
#define DOJA_BG_PD 256
#define DOJA_BG_X 0
#define DOJA_BG_Y 0
#define DOJA_SCALE_MODE_TEXT "native"
#define STANDALONE_CLASSPATH "@embedded"
#define STANDALONE_JAR_FILENAME "game.jar"
#define STANDALONE_NDS_GAME_CODE "####"
#define STANDALONE_APP_STORAGE_CODE "D0JA"
#define STANDALONE_NDS_INTERNAL_TITLE "DOJAEMPTY"
#define STANDALONE_OUTPUT_BASENAME "unprepared_doja_v48"
#define STANDALONE_SHORT_SAVE_NAME "D0JA.SAV"
#define STANDALONE_SHORT_SAVE_PATH "fat:/D0JA.SAV"
#define STANDALONE_SAVE_PATH "fat:/unprepared_doja_v48.sav"
#define STANDALONE_RMS_SAVE_PATH "fat:/unprepared_doja_v48.rms"
#define STANDALONE_LEGACY_SAVE_PATH "fat:/D0JA.DJS"
#define STANDALONE_SAVE_MODE_TEXT "RAM-FIRST SAVE"
#define DOJA_SCRATCHPAD_SIZE 0
#define DOJA_SCRATCHPAD_CRC32 0x00000000UL
#define DOJA_SCRATCHPAD_PACKED_SIZE 0
#define DOJA_SCRATCHPAD_WRAPPER_SIZE 0
#define DOJA_SCRATCHPAD_CODEC_LZ77 1
#define DOJA_COMPAT_CORPSE_PARTY 0
#define STANDALONE_PROPERTIES_TEXT ""
#endif
